// <auto-generated />
using System;
using KnowledgeOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnowledgeOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KnowledgeOpsDbContext))]
    [Migration("20260530202303_AddAnswerFeedbackTable")]
    partial class AddAnswerFeedbackTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeOps.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("audit_log_entry_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("event_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("message");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("severity");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_audit_log_entries");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_audit_log_entries_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_audit_log_entries_created_at");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_audit_log_entries_event_type");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_audit_log_entries_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_audit_log_entries_user_id");

                    b.ToTable("audit_log_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_audit_log_entries_severity", "[severity] IN (N'Info', N'Warning', N'Error', N'Critical')");
                        });
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Chat.AnswerFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("answer_feedback_id");

                    b.Property<Guid>("ChatInteractionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chat_interaction_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("rating");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_answer_feedback");

                    b.HasIndex("ChatInteractionId")
                        .HasDatabaseName("IX_answer_feedback_chat_interaction_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_answer_feedback_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_answer_feedback_user_id");

                    b.HasIndex("ChatInteractionId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_answer_feedback_chat_interaction_id_user_id");

                    b.HasIndex("OrganizationId", "Rating")
                        .HasDatabaseName("IX_answer_feedback_organization_id_rating");

                    b.ToTable("answer_feedback", null, t =>
                        {
                            t.HasCheckConstraint("CK_answer_feedback_rating", "[rating] IN (N'Useful', N'NotUseful')");
                        });
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Chat.ChatInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chat_interaction_id");

                    b.Property<string>("AiModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ai_model");

                    b.Property<string>("AiProvider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ai_provider");

                    b.Property<int>("AnswerState")
                        .HasColumnType("int")
                        .HasColumnName("answer_state");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer_text");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("estimated_cost");

                    b.Property<long?>("GenerationLatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("generation_latency_ms");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ProviderFailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("provider_failure_code");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionTextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("question_text_hash");

                    b.Property<int>("RetrievalCandidateCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("retrieval_candidate_count");

                    b.Property<long?>("RetrievalLatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("retrieval_latency_ms");

                    b.Property<Guid?>("RetrievalQueryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("retrieval_query_id");

                    b.Property<int?>("TokenUsageInput")
                        .HasColumnType("int")
                        .HasColumnName("token_usage_input");

                    b.Property<int?>("TokenUsageOutput")
                        .HasColumnType("int")
                        .HasColumnName("token_usage_output");

                    b.Property<long?>("TotalLatencyMs")
                        .HasColumnType("bigint")
                        .HasColumnName("total_latency_ms");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_chat_interactions");

                    b.HasIndex("AnswerState")
                        .HasDatabaseName("IX_chat_interactions_answer_state");

                    b.HasIndex("ChatSessionId")
                        .HasDatabaseName("IX_chat_interactions_chat_session_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_chat_interactions_user_id");

                    b.HasIndex("OrganizationId", "CreatedAt")
                        .HasDatabaseName("IX_chat_interactions_organization_id_created_at");

                    b.ToTable("chat_interactions", (string)null);
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Chat.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chat_session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("LastInteractionAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_interaction_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_chat_sessions");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_chat_sessions_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_chat_sessions_user_id");

                    b.HasIndex("OrganizationId", "CreatedAt")
                        .HasDatabaseName("IX_chat_sessions_organization_id_created_at");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Chat.Citation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("citation_id");

                    b.Property<Guid>("ChatInteractionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chat_interaction_id");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chunk_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("document_title");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int")
                        .HasColumnName("page_number");

                    b.Property<int>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("rank");

                    b.Property<double?>("RelevanceScore")
                        .HasColumnType("float")
                        .HasColumnName("relevance_score");

                    b.Property<string>("SectionLabel")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("section_label");

                    b.HasKey("Id")
                        .HasName("PK_citations");

                    b.HasIndex("ChatInteractionId")
                        .HasDatabaseName("IX_citations_chat_interaction_id");

                    b.HasIndex("ChunkId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_citations_document_id");

                    b.HasIndex("OrganizationId", "ChatInteractionId")
                        .HasDatabaseName("IX_citations_organization_id_chat_interaction_id");

                    b.ToTable("citations", (string)null);
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Documents.ChunkEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chunk_embedding_id");

                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chunk_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IndexFailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("index_failure_reason");

                    b.Property<string>("IndexStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("index_status");

                    b.Property<DateTime?>("IndexedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("indexed_at");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("model_name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("provider_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("VectorData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vector_data");

                    b.Property<int?>("VectorDimensions")
                        .HasColumnType("int")
                        .HasColumnName("vector_dimensions");

                    b.HasKey("Id")
                        .HasName("PK_chunk_embeddings");

                    b.HasIndex("ChunkId")
                        .IsUnique()
                        .HasDatabaseName("UX_chunk_embeddings_chunk_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_chunk_embeddings_organization_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_chunk_embeddings_status");

                    b.HasIndex("OrganizationId", "IndexStatus")
                        .HasDatabaseName("IX_chunk_embeddings_organization_index_status");

                    b.HasIndex("ProviderName", "ModelName")
                        .HasDatabaseName("IX_chunk_embeddings_provider_model");

                    b.ToTable("chunk_embeddings", (string)null);
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<bool>("IsRetrievalEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_retrieval_enabled");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_at");

                    b.Property<DateTime?>("ProcessingStartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("processing_started_at");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("processing_status");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("storage_location");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("PK_documents");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_documents_deleted_at");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_documents_organization_id");

                    b.HasIndex("ProcessingStatus")
                        .HasDatabaseName("IX_documents_processing_status");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("IX_documents_uploaded_at");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("IX_documents_uploaded_by_user_id");

                    b.HasIndex("OrganizationId", "ProcessingStatus", "IsRetrievalEnabled")
                        .HasDatabaseName("IX_documents_retrieval_eligibility");

                    b.ToTable("documents", null, t =>
                        {
                            t.HasCheckConstraint("CK_documents_processing_status", "[processing_status] IN (N'Uploaded', N'Processing', N'Processed', N'Failed')");
                        });
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Documents.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chunk_id");

                    b.Property<int?>("CharacterLength")
                        .HasColumnType("int")
                        .HasColumnName("character_length");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int")
                        .HasColumnName("chunk_index");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("document_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("int")
                        .HasColumnName("page_number");

                    b.Property<string>("SectionLabel")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("section_label");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<int?>("TokenEstimate")
                        .HasColumnType("int")
                        .HasColumnName("token_estimate");

                    b.HasKey("Id")
                        .HasName("PK_document_chunks");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_document_chunks_deleted_at");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_document_chunks_document_id");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_document_chunks_organization_id");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("UX_document_chunks_document_index");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_organizations");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_organizations_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_organizations_status");

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasCheckConstraint("CK_organizations_name_not_empty", "LEN(LTRIM(RTRIM([name]))) > 0");

                            t.HasCheckConstraint("CK_organizations_status", "[status] IN (N'Active', N'Disabled')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Asteria Support Group",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Boreal Contact Services",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_users");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_users_deleted_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_users_email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_users_organization_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_users_status");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_status", "[status] IN (N'Pending', N'Active', N'Disabled')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa0001-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Agent A",
                            Email = "agent.a@asteria.example.com",
                            OrganizationId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Supervisor A",
                            Email = "supervisor.a@asteria.example.com",
                            OrganizationId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0003-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "KnowledgeAdmin A",
                            Email = "knowledgeadmin.a@asteria.example.com",
                            OrganizationId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0004-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Manager A",
                            Email = "manager.a@asteria.example.com",
                            OrganizationId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0005-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin A",
                            Email = "admin.a@asteria.example.com",
                            OrganizationId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-bbbb-4bbb-8bbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Agent B",
                            Email = "agent.b@boreal.example.com",
                            OrganizationId = new Guid("22222222-2222-4222-8222-222222222222"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0002-bbbb-4bbb-8bbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin B",
                            Email = "admin.b@boreal.example.com",
                            OrganizationId = new Guid("22222222-2222-4222-8222-222222222222"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Users.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_user_roles");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("IX_user_roles_assigned_by_user_id");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("IX_user_roles_role_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_roles_user_id");

                    b.HasIndex("UserId", "RoleName")
                        .IsUnique()
                        .HasDatabaseName("UX_user_roles_user_role");

                    b.ToTable("user_roles", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_roles_role_name", "[role_name] IN (N'Agent', N'Supervisor', N'KnowledgeAdmin', N'Manager', N'Admin')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccc0001-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Agent",
                            UserId = new Guid("aaaa0001-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccc0002-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Supervisor",
                            UserId = new Guid("aaaa0002-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccc0003-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "KnowledgeAdmin",
                            UserId = new Guid("aaaa0003-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccc0004-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Manager",
                            UserId = new Guid("aaaa0004-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccc0005-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Admin",
                            UserId = new Guid("aaaa0005-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccc0006-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Agent",
                            UserId = new Guid("bbbb0001-bbbb-4bbb-8bbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("cccc0007-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Admin",
                            UserId = new Guid("bbbb0002-bbbb-4bbb-8bbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Audit.AuditLogEntry", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_audit_log_entries_organizations_organization_id");

                    b.HasOne("KnowledgeOps.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_audit_log_entries_users_user_id");
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Chat.AnswerFeedback", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Chat.ChatInteraction", null)
                        .WithMany()
                        .HasForeignKey("ChatInteractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_answer_feedback_chat_interactions_chat_interaction_id");

                    b.HasOne("KnowledgeOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_answer_feedback_organizations_organization_id");

                    b.HasOne("KnowledgeOps.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_answer_feedback_users_user_id");
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Chat.ChatInteraction", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Chat.ChatSession", null)
                        .WithMany()
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_chat_interactions_chat_sessions_chat_session_id");

                    b.HasOne("KnowledgeOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_chat_interactions_organizations_organization_id");

                    b.HasOne("KnowledgeOps.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_chat_interactions_users_user_id");
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Chat.ChatSession", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_chat_sessions_organizations_organization_id");

                    b.HasOne("KnowledgeOps.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_chat_sessions_users_user_id");
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Chat.Citation", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Chat.ChatInteraction", null)
                        .WithMany()
                        .HasForeignKey("ChatInteractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_citations_chat_interactions_chat_interaction_id");

                    b.HasOne("KnowledgeOps.Domain.Documents.DocumentChunk", null)
                        .WithMany()
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_citations_document_chunks_chunk_id");

                    b.HasOne("KnowledgeOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_citations_organizations_organization_id");
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Documents.ChunkEmbedding", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Documents.DocumentChunk", null)
                        .WithMany()
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_chunk_embeddings_document_chunks_chunk_id");

                    b.HasOne("KnowledgeOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_chunk_embeddings_organizations_organization_id");
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Documents.Document", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_documents_organizations_organization_id");

                    b.HasOne("KnowledgeOps.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_documents_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Documents.DocumentChunk", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_document_chunks_documents_document_id");

                    b.HasOne("KnowledgeOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_document_chunks_organizations_organization_id");
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Users.User", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_users_organizations_organization_id");
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Users.UserRole", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_user_roles_users_assigned_by_user_id");

                    b.HasOne("KnowledgeOps.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_user_roles_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
