// <auto-generated />
using System;
using KnowledgeOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnowledgeOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KnowledgeOpsDbContext))]
    [Migration("20260525190410_SeedFictionalOrganizationsAndPersonas")]
    partial class SeedFictionalOrganizationsAndPersonas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeOps.Domain.Audit.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("audit_log_entry_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("entity_type");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("event_type");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("message");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("severity");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_audit_log_entries");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_audit_log_entries_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_audit_log_entries_created_at");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_audit_log_entries_event_type");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_audit_log_entries_organization_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_audit_log_entries_user_id");

                    b.ToTable("audit_log_entries", null, t =>
                        {
                            t.HasCheckConstraint("CK_audit_log_entries_severity", "[severity] IN (N'Info', N'Warning', N'Error', N'Critical')");
                        });
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_organizations");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_organizations_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_organizations_status");

                    b.ToTable("organizations", null, t =>
                        {
                            t.HasCheckConstraint("CK_organizations_name_not_empty", "LEN(LTRIM(RTRIM([name]))) > 0");

                            t.HasCheckConstraint("CK_organizations_status", "[status] IN (N'Active', N'Disabled')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Asteria Support Group",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222222"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Boreal Contact Services",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_users");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("IX_users_deleted_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_users_email");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("IX_users_organization_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_users_status");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_status", "[status] IN (N'Pending', N'Active', N'Disabled')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa0001-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Agent A",
                            Email = "agent.a@asteria.example.com",
                            OrganizationId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Supervisor A",
                            Email = "supervisor.a@asteria.example.com",
                            OrganizationId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0003-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "KnowledgeAdmin A",
                            Email = "knowledgeadmin.a@asteria.example.com",
                            OrganizationId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0004-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Manager A",
                            Email = "manager.a@asteria.example.com",
                            OrganizationId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aaaa0005-aaaa-4aaa-8aaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin A",
                            Email = "admin.a@asteria.example.com",
                            OrganizationId = new Guid("11111111-1111-4111-8111-111111111111"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-bbbb-4bbb-8bbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Agent B",
                            Email = "agent.b@boreal.example.com",
                            OrganizationId = new Guid("22222222-2222-4222-8222-222222222222"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bbbb0002-bbbb-4bbb-8bbb-bbbbbbbbbbbb"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin B",
                            Email = "admin.b@boreal.example.com",
                            OrganizationId = new Guid("22222222-2222-4222-8222-222222222222"),
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Users.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_user_roles");

                    b.HasIndex("AssignedByUserId")
                        .HasDatabaseName("IX_user_roles_assigned_by_user_id");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("IX_user_roles_role_name");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_user_roles_user_id");

                    b.HasIndex("UserId", "RoleName")
                        .IsUnique()
                        .HasDatabaseName("UX_user_roles_user_role");

                    b.ToTable("user_roles", null, t =>
                        {
                            t.HasCheckConstraint("CK_user_roles_role_name", "[role_name] IN (N'Agent', N'Supervisor', N'KnowledgeAdmin', N'Manager', N'Admin')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccc0001-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Agent",
                            UserId = new Guid("aaaa0001-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccc0002-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Supervisor",
                            UserId = new Guid("aaaa0002-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccc0003-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "KnowledgeAdmin",
                            UserId = new Guid("aaaa0003-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccc0004-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Manager",
                            UserId = new Guid("aaaa0004-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccc0005-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Admin",
                            UserId = new Guid("aaaa0005-aaaa-4aaa-8aaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccc0006-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Agent",
                            UserId = new Guid("bbbb0001-bbbb-4bbb-8bbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("cccc0007-cccc-4ccc-8ccc-cccccccccccc"),
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Admin",
                            UserId = new Guid("bbbb0002-bbbb-4bbb-8bbb-bbbbbbbbbbbb")
                        });
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Audit.AuditLogEntry", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_audit_log_entries_organizations_organization_id");

                    b.HasOne("KnowledgeOps.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_audit_log_entries_users_user_id");
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Users.User", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_users_organizations_organization_id");
                });

            modelBuilder.Entity("KnowledgeOps.Domain.Users.UserRole", b =>
                {
                    b.HasOne("KnowledgeOps.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_user_roles_users_assigned_by_user_id");

                    b.HasOne("KnowledgeOps.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_user_roles_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
