// <auto-generated />
using KnowledgeOps.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KnowledgeOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KnowledgeOpsDbContext))]
    [Migration("20260528000001_CreateChatSessionsAndInteractions")]
    partial class CreateChatSessionsAndInteractions
    {
    }
}
